name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  verify:
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: configuring system for go project
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      
      - name: install direct dependencies
        run: go mod download

      - name: install indirect dependencies
        run: build/installIndirectDependencies.sh

      - name: linting
        run: golangci-lint run
      
      - name: fmtcheck
        run: make fmtcheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: running unit tests
        run: make test-cov

      - name: pushing code coverage report to codecov
        run: build/publishCodeCoverage.sh

      - name: setting up for integration testing
        run: build/setupForITs.sh

      - name: running integration tests
        run: make test-int-cov

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: setup semantic-release
        run: build/setupSR.sh

      - name: release using semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
